services:

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes:
      - ./data/n8n:/home/node/.n8n
    depends_on:
      - mongo
      - qdrant

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - ./data/mongo:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html

  servicedesk:
    image: nginx:latest
    container_name: servicedesk
    ports:
      - "8081:80"
    volumes:
      - ./servicedesk:/usr/share/nginx/html

  repository:
    image: nginx:latest
    container_name: repository
    ports:
      - "8082:80"
    volumes:
      - ./repository:/usr/share/nginx/html

  api:
    build: ./api
    container_name: fastapi
    ports:
      - "8001:8000"
    volumes:
      - ./api:/app
      - ./servicedesk/categorias.json:/servicedesk/categorias.json:ro
    depends_on:
      - mongo

volumes:
  qdrant_data:
